[
  {
    added_by: null,
    cal_weight_200: 105.2,
    calcium_in_mg: 14,
    calories: 189,
    carb_in_g: 15.4,
    cholestrol_in_mg: 0,
    created_at: '2023-03-04T17:22:44.000000Z',
    deleted_at: null,
    details: {
      id: 28,
      multiplication: 1,
      selectedDropDown: '1 oz (28 g)',
      totalCalcium: '3.92',
      totalCalorie: '52.92',
      totalCarb: '4.31',
      totalCholesterol: '0.00',
      totalFat: '3.30',
      totalFiber: '0.78',
      totalIron: '0.48',
      totalMonounsaturatedFat: '2.32',
      totalPolyunsaturatedFat: '0.59',
      totalPotassium: '49.67',
      totalProtein: '1.74',
      totalSaturatedFat: '0.22',
      totalSodium: '85.06',
      totalSugar: '0.17',
      totalTransFat: '0.03',
      totalVitaminAIU: '0.00',
      totalVitaminARAE: '0.00',
      totalVitaminC: '0.00',
      totalVitaminD: '0.00',
    },
    fat_in_g: 11.8,
    fiber_in_g: 2.8,
    food_group: 'Breakfast',
    food_name: 'Vada',
    id: 20373,
    image: 'http://admin.fitaraise.com/storage/uploads/app_images/no_image.png',
    iron_in_mg: 1.7,
    is_active: 1,
    monounsaturated_fat_in_g: 8.3,
    polyunsaturated_fat_in_g: 2.1,
    potassium_in_mg: 177.4,
    protein_in_g: 6.2,
    saturated_fat_in_g: 0.8,
    serving_desc_1: '1 oz',
    serving_desc_2: '1 piece',
    serving_desc_3: '3 pieces (mean serving weight, aggregated over brands)',
    serving_desc_4: null,
    serving_desc_5: null,
    serving_desc_6: null,
    serving_desc_7: null,
    serving_desc_8: null,
    serving_desc_9: null,
    serving_size: '100 grams',
    serving_weight_1: 28,
    serving_weight_2: 50,
    serving_weight_3: 180,
    serving_weight_4: null,
    serving_weight_5: null,
    serving_weight_6: null,
    serving_weight_7: null,
    serving_weight_8: null,
    serving_weight_9: null,
    sodium_in_mg: 303.8,
    sugar_in_g: 0.6,
    trans_fat_in_g: 0.1,
    updated_at: '2023-03-04T17:22:44.000000Z',
    vitamin_a_in_mg: null,
    vitamin_a_iu: null,
    vitamin_a_rae_mg: null,
    vitamin_c_in_mg: null,
    vitamin_d_mg: 0,
    weight_in_g: 100,
  },
  {
    '0': '1',
    '1': ' ',
    '10': '0',
    '11': ' ',
    '12': 'g',
    '13': ')',
    '2': 'p',
    '3': 'i',
    '4': 'e',
    '5': 'c',
    '6': 'e',
    '7': ' ',
    '8': '(',
    '9': '5',
    details: {
      id: 37,
      multiplication: '10',
      selectedDropDown: '1 piece (50 g)',
      totalCalcium: '70.00',
      totalCalorie: '945.00',
      totalCarb: '77.00',
      totalCholesterol: '0.00',
      totalFat: '59.00',
      totalFiber: '14.00',
      totalIron: '8.50',
      totalMonounsaturatedFat: '41.50',
      totalPolyunsaturatedFat: '10.50',
      totalPotassium: '887.00',
      totalProtein: '31.00',
      totalSaturatedFat: '4.00',
      totalSodium: '1519.00',
      totalSugar: '3.00',
      totalTransFat: '0.50',
      totalVitaminAIU: '0.00',
      totalVitaminARAE: '0.00',
      totalVitaminC: '0.00',
      totalVitaminD: '0.00',
    },
  },
];
