{ "desc_num_food_tbl":["The desc num food tbl field is required."],
  "food_id": ["The food id field is required."],
   "id": ["The id field is required."],
    "meal_type": ["The meal type field is required."],
     "quantity": ["The quantity field is required."],
      "serving_desc_id": ["The serving desc id field is required."],
       "taken_weight": ["The taken weight field is required."]
     },
     {
        "food_id": 20373,
         "meal_type": 1,
          "quantity": 1,
           "serving_desc_id": 37,
            "taken_weight": 100,
            "id":1000,
            "desc_num_food_tbl":5

        }

        {
         "added_by": null,
         "cal_weight_200": 105.2,
          "calcium_in_mg": 14,
           "calories": 189,
            "carb_in_g": 15.4,
             "cholestrol_in_mg": 0,
              "created_at": "2023-03-04T17:22:44.000000Z",
               "deleted_at": null,
                "fat_in_g": 11.8,
                 "fiber_in_g": 2.8,
                  "food_group": "Breakfast",
                   "food_name": "Vada",
                    "id": 20373, 
                    "image": "http://admin.fitaraise.com/storage/uploads/app_images/no_image.png",
                     "iron_in_mg": 1.7,
                      "is_active": 1,
                       "monounsaturated_fat_in_g": 8.3,
                        "polyunsaturated_fat_in_g": 2.1,
                         "potassium_in_mg": 177.4,
                          "protein_in_g": 6.2,
                           "saturated_fat_in_g": 0.8,
                            "serving_desc_1": "1 oz",
                             "serving_desc_2": "1 piece",
                              "serving_desc_3": "3 pieces (mean serving weight, aggregated over brands)",
                               "serving_desc_4": null,
                                "serving_desc_5": null,
                                 "serving_desc_6": null,
                                  "serving_desc_7": null,
                                  "serving_desc_8": null,
                                   "serving_desc_9": null,
                                    "serving_size": "100 grams",
                                     "serving_weight_1": 28,
                                      "serving_weight_2": 50,
                                       "serving_weight_3": 180,
                                        "serving_weight_4": null,
                                         "serving_weight_5": null,
                                          "serving_weight_6": null,
                                           "serving_weight_7": null,
                                            "serving_weight_8": null,
                                             "serving_weight_9": null,
                                              "sodium_in_mg": 303.8,
                                               "sugar_in_g": 0.6,
                                                "trans_fat_in_g": 0.1,
                                                 "updated_at": "2023-03-04T17:22:44.000000Z",
                                                  "vitamin_a_in_mg": null,
                                                   "vitamin_a_iu": null,
                                                    "vitamin_a_rae_mg": null,
                                                     "vitamin_c_in_mg": null,
                                                      "vitamin_d_mg": 0,
                                                       "weight_in_g": 100
                                                      }